services:
  db:
    image: postgres:16-alpine
    container_name: deckforge_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: deckforge
      POSTGRES_PASSWORD: deckforge_pass
      POSTGRES_DB: deckforge
    ports:
      - "5432:5432"
    volumes:
      - deckforge_pgdata:/var/lib/postgresql/data

volumes:
  deckforge_pgdata:
